platform :ios, '16.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'

# REMOVE use_frameworks! completely for React Native modules
# use_frameworks!

target 'example' do
  use_react_native!(
    :path => '../node_modules/react-native'
  )

  # Your SDK - path is CORRECT
  pod 'react-native-videoid-sdk', :path => '../../ios'
  
  post_install do |installer|
    react_native_post_install(installer)
    
    # Fix for all targets
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Only exclude i386 (32-bit), NOT arm64
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
        config.build_settings['DEFINES_MODULE'] = 'YES'
        
        # Add React module support
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      end
    end
  end
end