
# example/ios/podfile
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

ENV['RCT_NEW_ARCH_ENABLED'] = '1'
# ENV['RCT_NEW_ARCH_ENABLED'] = '0'

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


pre_install do |installer|
  require 'fileutils'

  spec_path = File.expand_path('../../VideoidSdk.podspec', __dir__)
  spec      = Pod::Specification.from_file(spec_path)

  local_dir  = File.join(__dir__, 'Pods', 'Local Podspecs')
  FileUtils.mkdir_p(local_dir)

  json_path = File.join(local_dir, 'VideoidSdk.podspec.json')
  File.write(json_path, spec.to_pretty_json)
end

target 'VideoidSdkExample' do
  config = use_native_modules!

#  use_react_native!(
#    :path => config[:reactNativePath],
#    :app_path => "#{Pod::Config.instance.installation_root}/.."
#  )
  
  use_react_native!(
      :path => config[:reactNativePath],
      :hermes_enabled => true,
      :fabric_enabled => true,
      :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
